#ifndef BYTEVIEW_COLOR_H
#define BYTEVIEW_COLOR_H


#include <raylib.h>
#include <raymath.h>
#include <rlgl.h>


typedef enum ByteViewColorType {
    BYTEVIEW_COLOR_TYPE_NONE = 0,

    // 8 bits
    BYTEVIEW_COLOR_TYPE_R8,
    BYTEVIEW_COLOR_TYPE_G8,
    BYTEVIEW_COLOR_TYPE_B8,
    BYTEVIEW_COLOR_TYPE_A8,
    BYTEVIEW_COLOR_TYPE_Y8,

    // 16 bits
    BYTEVIEW_COLOR_TYPE_RG88,
    BYTEVIEW_COLOR_TYPE_GR88,
    BYTEVIEW_COLOR_TYPE_Y10,
    BYTEVIEW_COLOR_TYPE_Y12,
    BYTEVIEW_COLOR_TYPE_RGB332,
    BYTEVIEW_COLOR_TYPE_RGBA2222,
    BYTEVIEW_COLOR_TYPE_RGB565,
    BYTEVIEW_COLOR_TYPE_BGR565,
    BYTEVIEW_COLOR_TYPE_XRGB1555,
    BYTEVIEW_COLOR_TYPE_ARGB1555,
    BYTEVIEW_COLOR_TYPE_RGBX5551,
    BYTEVIEW_COLOR_TYPE_RGBA5551,
    BYTEVIEW_COLOR_TYPE_RGBX4444,
    BYTEVIEW_COLOR_TYPE_XRGB4444,
    BYTEVIEW_COLOR_TYPE_RGBA4444,
    BYTEVIEW_COLOR_TYPE_ARGB4444,

    // 24 bits
    BYTEVIEW_COLOR_TYPE_RGB888,
    BYTEVIEW_COLOR_TYPE_BGR888,
    BYTEVIEW_COLOR_TYPE_VUY888,

    // 32 bits
    BYTEVIEW_COLOR_TYPE_RG1616,
    BYTEVIEW_COLOR_TYPE_XRGB8888,
    BYTEVIEW_COLOR_TYPE_XBGR8888,
    BYTEVIEW_COLOR_TYPE_RGBX8888,
    BYTEVIEW_COLOR_TYPE_BGRX8888,
    BYTEVIEW_COLOR_TYPE_ARGB8888,
    BYTEVIEW_COLOR_TYPE_ABGR8888,
    BYTEVIEW_COLOR_TYPE_RGBA8888,
    BYTEVIEW_COLOR_TYPE_BGRA8888,
    BYTEVIEW_COLOR_TYPE_XVUY8888,
    BYTEVIEW_COLOR_TYPE_XRGB2101010,
    BYTEVIEW_COLOR_TYPE_XBGR2101010,
    BYTEVIEW_COLOR_TYPE_RGBX1010102,
    BYTEVIEW_COLOR_TYPE_BGRX1010102,
    BYTEVIEW_COLOR_TYPE_ARGB2101010,
    BYTEVIEW_COLOR_TYPE_ABGR2101010,
    BYTEVIEW_COLOR_TYPE_RGBA1010102,
    BYTEVIEW_COLOR_TYPE_BGRA1010102,

    // 48 bits
    BYTEVIEW_COLOR_TYPE_RGB161616,
    BYTEVIEW_COLOR_TYPE_BGR161616,

    // 64 bits
    BYTEVIEW_COLOR_TYPE_RGBA16161616,
    BYTEVIEW_COLOR_TYPE_BGRA16161616,
    BYTEVIEW_COLOR_TYPE_ARGB16161616,
    BYTEVIEW_COLOR_TYPE_ABGR16161616,

    // Extra 
    BYTEVIEW_COLOR_TYPE_GRADIENT,
    BYTEVIEW_COLOR_TYPE_CLASS,
    BYTEVIEW_COLOR_TYPE_COUNT
} ByteViewColorType;

Color GetByteViewColor(const unsigned char* fileData, unsigned int fileSize, unsigned int byteIndex, ByteViewColorType colorType);
const char* GetByteViewColorTypeName(ByteViewColorType byteViewColorType);

#endif
